### ISSUE TITLE
Hover tooltip data

### ISSUE THREAD

**Issue by alxjzx100** [themustafaomar/jsvectormap#101]
Is there any way to change hover tooltip data?
I want to show additional data when user is hover region.

**Comment by themustafaomar** [comment]
Hi @alxjzx100 

Yes, you can do this by listening to `onRegionTooltipShow` event, and changing the tooltip content.

```js
const map = new jsVectorMap({
  ...
  onRegionTooltipShow(event, tooltip, code) {
    if (code === 'CA') {
      tooltip.text(`
        <h3>Canada</h3>
        <p>Canada is a country in North America.<br>Its ten provinces and three territories extend from the Atlantic Ocean to the Pacific Ocean</p>
      `, true)
    }
  },
  ...
});
```

Demo: https://codepen.io/themustafaomar/pen/OJvqoRO
