### ISSUE TITLE
Bug on touch screens

### ISSUE THREAD

**Issue by Valentine13** [themustafaomar/jsvectormap#104]
If you tap on a country and then start moving or zooming the map, firstly, the active tooltip disappears, and secondly, subsequent taps on the same country will not work until you "reset" this bug by tapping on another area on the map. What can be done, so that moving and zooming are immediately reset the country selection?

**Comment by themustafaomar** [comment]
It looks like the zoom not working on mobile at all starting from v1.4.0, this is going to be fixed as soon as possible.
