### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by weekywhawha** [themustafaomar/jsvectormap#117]
When using the option:

`showTooltip: false`

the following error is displayed on the browser console:
Uncaught TypeError: Cannot read properties of undefined (reading 'text')

related to the setupElementEvents.js mouseover event

`if (event.type === 'mouseover') {
      data.element.hover(true)
      map.tooltip.text(data.tooltipText)
      map._emit(data.event, [event, map.tooltip, data.code])`

**Comment by themustafaomar** [comment]
Thanks for reporting this issue, the fix will be available by the next week  in v1.5.2
