### ISSUE TITLE
Touch support is lacking

### ISSUE THREAD

**Issue by sknick** [themustafaomar/jsvectormap#118]
While I can drag the map when on mobile, I can't zoom in or out by pinching as one might expect. I saw an issue where this may be a new bug, so I thought I'd document it in an issue. Note that I have tried explicitly setting `bindTouchEvents` property to `true` as well.

**Comment by themustafaomar** [comment]
Hi @sknick 

Yes it doesn't work currently but it's fixed at #114 #104 this fix will be available by the next week with v1.5.2, stay tuned!

**Comment by sknick** [comment]
What happened to v1.5.2?

**Comment by themustafaomar** [comment]
I'm really sorry for the late response, the weekends weren't happy for me, it's available now please update to v1.5.2.
