### ISSUE TITLE
Error when dragging in mobile

### ISSUE THREAD

**Issue by sknick** [themustafaomar/jsvectormap#126]
When I attempt to drag (pan) the map in mobile, the following error is shown in the console and panning doesn't work:

```
jsvectormap.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'hide')
    at HTMLDivElement.h (jsvectormap.min.js:1:14459)
```

This appears to be a new issue in 1.5.2.

**Comment by themustafaomar** [comment]
Thanks for reporting this bug, please update to v1.5.3

**Comment by sknick** [comment]
I'm still getting the same error after upgrading. I'm using the mobile emulator in Chrome if it helps.

**Comment by themustafaomar** [comment]
Don't use the Chrome emulator, does it work on mobile devices?

**Comment by sknick** [comment]
Well, that's problematic since I develop and test via the emulators before deploying. Is there any reason it can't be made to work with the emulators?

**Comment by themustafaomar** [comment]
Please consider giving it a try in actual mobile devices, and if it's not working I'm ready to bring the issue back and fix it.
