### ISSUE TITLE
Error when dragging in mobile

### ISSUE THREAD

**Issue by sknick** [themustafaomar/jsvectormap#128]
When I attempt to drag (pan) the map in mobile, the following error is shown in the console and panning doesn't work:

```
jsvectormap.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'hide')
    at HTMLDivElement.h (jsvectormap.min.js:1:14459)
```

This appears to be a new issue in 1.5.2 that 1.5.3 unfortunately didn't fix.

**Comment by themustafaomar** [comment]
I think this is working now isn't it, if the isse still persists please let me know.
