### ISSUE TITLE
jsvmap-tooltip not cleaned up properly

### ISSUE THREAD

**Issue by jepperaskdk** [themustafaomar/jsvectormap#13]
Not sure if this is related to Angular.

I've added a navigate in `onMarkerSelected`, but the tooltip being hovered when clicking remains in DOM. Is there a way to destroy the map before navigating? As a workaround I'm using this before navigating:
```window.document.querySelectorAll(".jsvmap-tooltip").forEach(n => n.remove());```

**Comment by themustafaomar** [comment]
Hi @jepperaskdk 

Actually, I had the same problem and more when I navigate to another route in my Vue apps.

So, I decided to introduce a new method ```destroy``` to remove event listeners, tooltip, and everything related in the next version which hopefully will be released this week.

**Comment by themustafaomar** [comment]
v1.2.0 is released.

**Comment by themustafaomar** [comment]
v1.2.0 is released with ```destroy``` method.

**Comment by jepperaskdk** [comment]
@themustafaomar Cool, thank you for a quick fix. Works perfectly. :+1:

**Comment by maryjen** [comment]
@jepperaskdk How do you show the tooltip with the mouse cursor? i'm using jsvectormap in a angular project and the tooltip is stuck on the left side blow the map, so not moving with the cursor
If i change the position of jvm-tooltip to relative it moves with the cursor, but too far away. 

See this example: https://stackblitz.com/edit/angular-interactiveworldmap
