### ISSUE TITLE
markers custom property

### ISSUE THREAD

**Issue by studiosacchetti** [themustafaomar/jsvectormap#14]
is it possile to add a custom propperties to markers so as to have those in tooltips box?

**Comment by themustafaomar** [comment]
Yes you can do this, please take a look at this example: https://codepen.io/themustafaomar/pen/bGwppPL?editors=1010

**Comment by studiosacchetti** [comment]
> 
> 
> Yes you can do this, please take a look at this example: https://codepen.io/themustafaomar/pen/bGwppPL?editors=1010

**Comment by studiosacchetti** [comment]
thx a lot!! great project!
