### ISSUE TITLE
event on tooltips lost focus

### ISSUE THREAD

**Issue by studiosacchetti** [themustafaomar/jsvectormap#15]
i'am using  this example
```
onMarkerTooltipShow: function (tooltip, index) {
            map.setSelected('regions', ['EG', 'RU', 'US']);
}
```
but i can't figure how to use clearSelectedRegions() when tooltips close or markers lost focus

Thx in advance

**Comment by themustafaomar** [comment]
Actually, you can't do that since there is no event fired when the tooltip is closed.

However, as a workaround, you can do this: https://codepen.io/themustafaomar/pen/yLaOMJe?editors=1010

Hope I got you right!

**Comment by studiosacchetti** [comment]
in my case i have different regions for each marker and then i had to change your code like that

```
onMarkerTooltipShow: function (tooltip, index) {
            map.setSelected('regions', markers[index].countries);
}

onLoaded(map) {
            map.container.delegate(
                    "circle.jsvmap-marker, text.jsvmap-marker",
                    "mouseout",
                    (e) => {
                if (e.type === "mouseout" ) {
                    map.clearSelectedRegions();
                }
            });
        },
```
and it work perfect, but it seem that regions are black and not colored as expected, any tips?

thx a lot for your time

**Comment by themustafaomar** [comment]
Styling the regions is the same as styling the markers.

```js
const map = new jsVectorMap({ 
  regionStyle: {
    initial: {
      stroke: "#676767",
      strokeWidth: 2.5,
      fill: '#ff5566',
      fillOpacity: 1,
    },
  }
})
```

Take a look at docs: https://themustafaomar.com/open-source/jsvectormap/docs/regions/
