### ISSUE TITLE
I'm not in Egypt even the map knows that

### ISSUE THREAD

**Issue by DanielTate** [themustafaomar/jsvectormap#156]
![jvm-docs vercel app_docs_sample-reflect-user-location](https://github.com/themustafaomar/jsvectormap/assets/2068815/b9f117fa-ccc5-4e34-a71b-ffc3717660e8)

**Comment by themustafaomar** [comment]
Hi @DanielTate 

Looks like I was hard-coding the marker's name with Egypt, because the browser's default geolocation doesn't provide the location name.

Anyway, I've just implemented another approach and updated the docs.

Thanks!
