### ISSUE TITLE
Focus on a specific region

### ISSUE THREAD

**Issue by nikhilkutinha** [themustafaomar/jsvectormap#2]
Hey there, 
was just wondering if it is possible to zoom (not highlight) into  a specific region. For instance, I can use the "focusOn" paramter in jVectorMap, set it to say "US" and the map would have loaded with the focus being on United States. 
Kind Regards.

**Comment by themustafaomar** [comment]
Working on it...
it will be available by tomorrow maybe, thanks.

**Comment by themustafaomar** [comment]
Done adding setFocus.
you can now set focus on a specific region or collection of regions.
```javascript
var map = new JsVectorMap({
  map: 'world',
  selector: '#map',
 // Set focus initially
  focusOn: {
    region: 'EG',
    // Or regions: ['EG', 'CN'],
    animate: true
  }
})
```
Set focus by some button.
```javascript
document.querySelector('#focus').addEventListener('click', () => {
  map.setFocus({ region: 'RU', animate: true })
})
```
Notice: CDN links in README isn't going to work currently.
if you want to work with CDN links, you can use the following.
https://unpkg.com/jsvectormap@1.0.4/dist/js/jsvectormap.min.js
