### ISSUE TITLE
Missing countries

### ISSUE THREAD

**Issue by BrettGregson** [themustafaomar/jsvectormap#22]
Any plans to add some of the missing small countries like Andorra, San Marino etc?

**Comment by themustafaomar** [comment]
Actually, I tried to create a new map with high detail but the file size was 1.15 MB!
after using [svgo](https://github.com/svg/svgo) library to optimize paths the file becomes 850KB, this still overkill.

However, someone already added the missing countries here:
https://github.com/matt-williams987/jvectormap-all-countries

**Comment by BrettGregson** [comment]
Nice! I'll look my side to see if I can make optimisations to the file and open a PR if I get it small enough
