### ISSUE TITLE
Continents Map

### ISSUE THREAD

**Issue by a-omla** [themustafaomar/jsvectormap#23]
I was wondering if there is a map or a way to import a map that just shows continents rather than countries

**Comment by a-omla** [comment]
nvm, I obtained a map from a repository of jvectormap maps and refactored the files to create a continents map.

Let me know if you would like me to pull create a pull request and I can provide the modified map files

**Comment by cdsaenz** [comment]
> nvm, I obtained a map from a repository of jvectormap maps and refactored the files to create a continents map.
> 
> Let me know if you would like me to pull create a pull request and I can provide the modified map files

Sorry do you have these maps available? They'd be of much use to me. Thanks a lot.
