### ISSUE TITLE
Drill-down in multi hierarchy map

### ISSUE THREAD

**Issue by mrhb** [themustafaomar/jsvectormap#3]
is it possible to Drill-down in a multi hierarchy map(like jvectormap)?

**Comment by themustafaomar** [comment]
Unfortunately not yet :(

**Comment by 1Map** [comment]
> Unfortunately not yet :(

Almost 3 years and still "not yet"

**Comment by themustafaomar** [comment]
#109 

> Looks like there are a lot of demand for this feature, I'll do my best to implement it, don't know when, but I'll consider it.
Thanks!
