### ISSUE TITLE
dist folder is empty

### ISSUE THREAD

**Issue by lhsaia** [themustafaomar/jsvectormap#32]
Hi

dist/css and dist/js folders are empty, they contain only .gitignore file.

**Comment by themustafaomar** [comment]
That's right, Github shouldn't have them, they exist when installing `Jsvectormap` via npm.

However, if you're cloning the repo and you want to have them.
run `npm i` to install the dependencies and run `npm run build` to build `dist/js/` `dist/css/`

Relevant issue: #9
