### ISSUE TITLE
Data visualization is not working

### ISSUE THREAD

**Issue by rushenn** [themustafaomar/jsvectormap#37]
I'm using the following code as instructed in the documentation but the visualization is not appearing on the map. The map is loading as expected with the default region color. I'm I missing anything?

```
const map = new jsVectorMap({
        selector: "#map",
        map: "world",
        draggable: false,
        zoomButtons: false,
        zoomOnScroll: false,
        regionStyle: {
            initial: {
                fill: "#FFEFD6",
                "fill-opacity": 1,
                stroke: "none"
            },
        },
        viusalizeData: {
            scale: ["#ecf0f1", "#7f8c8d"],
            values: {
                EG: 290,
                US: 100,
                CA: 120,
                BR: 75,
            }
        }
    });
```

**Comment by themustafaomar** [comment]
This is my bad sorry about that, there was a typo in the documentation.

I updated this page: https://themustafaomar.com/open-source/jsvectormap/docs/visualize-data

But didn't update the example at https://themustafaomar.com/open-source/jsvectormap/examples/data-visualization

It should be: `visualizeData` Not: `viusalizeData`

Related issue:  #30

**Comment by rushenn** [comment]
@themustafaomar Thank you very much.
