### ISSUE TITLE
Country code IL is labeled as Palestine

### ISSUE THREAD

**Issue by liyangguang** [themustafaomar/jsvectormap#39]
In `/dist/maps/world.js`, there's `IL:{path:"M507.76,203.05l0.4,-0.78l0.18,0.4l-0.33,1.03l0.52,0.44l0.68,-0.22l-0.86,3.6l-1.16,-3.32l0.59,-0.74l-0.03,-0.41ZM508.73,200.34l0.37,-1.02l0.64,0.0l0.52,-0.51l-0.49,1.53l-0.56,-0.24l-0.48,0.23Z",name:"Palestine"}`.

The label for Israel is now Palestine.

I cannot determine which file / package is this coming from. If `/dist/maps/world.js` is the source of truth file, I can send a pull request.

**Comment by themustafaomar** [comment]
Really hate to do this but [UPDATED](https://github.com/themustafaomar/jsvectormap/commit/d100b32ab7d96bf8b61fdc6713c8935a88eddc07).
