### ISSUE TITLE
Refreshing the map programatically 

### ISSUE THREAD

**Issue by rushenn** [themustafaomar/jsvectormap#41]
Is it possible to reload/refresh the map without reloading the page itself? Somthing like: 

```
const map = new jsVectorMap({ ... })
map.reload()
```

**Comment by themustafaomar** [comment]
I think everything is reactive in Jsvectormap, everything can be removed or added!

Could you please explain to me exactly what supposed to be done when calling the `reload` method?

Do you mean you want to destroy features and recreate them again 🤔?

**Comment by rushenn** [comment]
@themustafaomar Yes, I'm looking to destroy features and recreate the map again.

**Comment by themustafaomar** [comment]
You can destroy the map using `destroy` method, but unfortunately, you can't recreate it again, it's a very complex process.

However, you can manipulate the map there're some methods you can use to remove or create objects, like `markers` , `lines` , `series` and resetting the map etc...

Also as a workaround I created this pen I think this is what you want to achieve https://codepen.io/themustafaomar/pen/WNpVLoG?editors=0010

Notice I've just published a new version v1.3.2 please update.

**Comment by rushenn** [comment]
@themustafaomar Thank you very much, this is what I'm looking to achieve.

**Comment by rushenn** [comment]
@themustafaomar I'm having some issues while refreshing the map based on your example given using the above codepen. The above method was used to work with prior JsVectomap versions but with the latest version. Trying the same code with the latest version, I'm getting the following error,

`Uncaught Error: The method [reloadWith] already exists internally please use another name.`

Please check this codepen, I'm able to update the properties of the map only once. The next time, it gives the above error. I'm I missing anything here

**Comment by themustafaomar** [comment]
Hi @rushenn 

the `extend` method should be called once, avoid calling `extend` method inside an event.

**Comment by rushenn** [comment]
@themustafaomar This is great, never thought about the CSS way. Thanks for bringing this up.

**Comment by themustafaomar** [comment]
🎉🎉
