### ISSUE TITLE
custom map based on cities

### ISSUE THREAD

**Issue by rjjrbatarao** [themustafaomar/jsvectormap#43]
Hi this is a great library is there any tutorial on how to make a map of my city? we wanted to show locations of our wifi accesspoint but only countries and world available in dist.

**Comment by themustafaomar** [comment]
Unfortunately not, but:

you can use the Jvectormap converter https://jvectormap.com/documentation/gis-converter/ to do the job.

I didn't make a tutorial on how to use the Jvectormap converter cause I didn't use Python before.

This might help: https://github.com/datag/jvectormap/wiki/Map-converter-notes
