### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by vahidtakro** [themustafaomar/jsvectormap#46]
I get the following error when I want to use jsvectormap:
this is how I imported:

```
import { jsVectorMap } from '@/components/map/jsVectorMap'
import { Map } from '@/components/map/world'
```

![Captu;lre](https://user-images.githubusercontent.com/40500566/128861482-d3f7aa9f-704b-4ee4-ae21-5c89af888e60.JPG)

**Comment by themustafaomar** [comment]
I guess you're using React, Nextjs isn't it?

And Server-Side Rendering (SSR) is enabled, it seems that the Element not found because there is no a `window` object in Node js

If my guess is correct, first I've never worked with React but:

In Vue specifically Nuxtjs, we add a new plugin and disable SSR for this particular plugin as follows:

Nuxtjs config file `nuxt.config.js`

```js
...
plugins: [
  { src: '@/plugins/vuevectormap.js', mode: 'client' }
],
...
```

Create a new file in the plugins directory with a name vuevectormap.js

```js
// plugins/vuevectormap.js
import Vue from 'vue'
import VueVectorMap from 'vuevectormap'
import 'vuevectormap/src/scss/vuevectormap.scss'

// Import your preffered map.
require('jsvectormap/dist/maps/spain')

Vue.use(VueVectorMap)
```

Here's the Vue version https://github.com/themustafaomar/vuevectormap

I believe they're the same and you could implement this in your React project.

**Comment by vahidtakro** [comment]
> I guess you're using React, Nextjs isn't it?
> 
> And Server-Side Rendering (SSR) is enabled, it seems that the Element not found because there is no a `window` object in Node js
> 
> If my guess is correct, first I've never worked with React but:
> 
> In Vue specifically Nuxtjs, we add a new plugin and disable SSR for this particular plugin as follows:
> 
> Nuxtjs config file `nuxt.config.js`
> 
> ```js
> ...
> plugins: [
>   { src: '@/plugins/vuevectormap.js', mode: 'client' }
> ],
> ...
> ```
> 
> Create a new file in the plugins directory with a name vuevectormap.js
> 
> ```js
> // plugins/vuevectormap.js
> import Vue from 'vue'
> import VueVectorMap from 'vuevectormap'
> import 'vuevectormap/src/scss/vuevectormap.scss'
> 
> // Import your preffered map.
> require('jsvectormap/dist/maps/spain')
> 
> Vue.use(VueVectorMap)
> ```
> 
> Here's the Vue version https://github.com/themustafaomar/vuevectormap
> 
> I believe they're the same and you could implement this in your React project.

Thanks, yes I am using next.js and still very basic learner, I think it must be something related to webpack (plugin),
https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

**Comment by vahidtakro** [comment]
at least the error has changed now after adding the module:

```
Could not find a declaration file for module 'jsvectormap'. 'c:/Users/conta/Desktop/maskh/node_modules/jsvectormap/dist/js/jsvectormap.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/jsvectormap` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsvectormap';`ts(7016)
module "c:/Users/conta/Desktop/maskh/node_modules/jsvectormap/dist/js/jsvectormap.min"
```

**Comment by themustafaomar** [comment]
@vahidtakro 

Not exactly, here is how to disable SSR for a particular component check this:

https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by vahidtakro** [comment]
> @vahidtakro
> 
> Not exactly, here is how to disable SSR for a particular component check this:
> 
> https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

thanks, as I just checked with my other modules, they have a .d.ts file, which is required for next.js maybe? which is missing on this package. The error also says the same thing:
"add a new declaration (.d.ts) file containing `declare module 'jsvectormap';`"

**Comment by themustafaomar** [comment]
According to these answers, YES, check this:

https://stackoverflow.com/questions/41462729/typescript-react-could-not-find-a-declaration-file-for-module-react-material

**Comment by vahidtakro** [comment]
> According to these answers, YES, check this:
> 
> https://stackoverflow.com/questions/41462729/typescript-react-could-not-find-a-declaration-file-for-module-react-material

following the answers (except the one who used a little hack) I had to install it like this:
npm install @types/jsvectormap

but I get following error:


```
npm install @types/jsvectormap
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fjsvectormap - Not found
npm ERR! 404
npm ERR! 404  '@types/jsvectormap@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

**Comment by themustafaomar** [comment]
Ah, of course, there is no package called `@tpyes/jsvectormap`!

The typescript was just suggesting a wrong fix.

I suggest watching a video or reading an article a that explains how to install a JavaScript plugin with Nextjs, as I mentioned I didn't use React so I can't help here :(

Closing this issue as it's not related to Jsvectormap.
