### ISSUE TITLE
Dragging the map selects a region

### ISSUE THREAD

**Issue by crystalenka** [themustafaomar/jsvectormap#47]
Hi!

I am very grateful for this plugin, it's saved me a TON of time. I've just noticed a bug while I'm testing my map; if you click and drag the map with the mouse over a region, it selects the region. 

Is there any way to disable or modify this behavior, besides disabling dragging? Is there an onDrag event or something? (Also asking because I'd like to change the cursor when it's dragging.)

Thank you!
Crystal

**Comment by themustafaomar** [comment]
Thank you for reporting this bug!

I've just fixed the issue and released a new version please make sure to update to v1.3.3

As for dragging, unfortunately, there is no event fired when dragging the map.

However as a workaround you can do the following:

```js
const jvm = new jsVectorMap({
  selector: "#map",
  map: "world_merc",
  regionsSelectable: true,
  onLoaded(map) {
    const container = map.container

    // When dragging the map from anywhere inside the container, even if it is not a region.
    // container.on('mousedown', () => {
    //   console.log('Dragging!!')
    // })
    // .on('mouseup', () => {
    //   console.log('Released!!')
    // })

    // OR -> when dragging the region/s itself.
    // Using built-in delegate method is recommended because
    // all event listeners wrapped within it are removed automatically when the map is destroyed.
    container.delegate(".jvm-region", "mousedown mouseup", (event) => {
      if (event.type === "mousedown") {
        console.log("Region is being dragged!!")
      } else {
        console.log("Region released!!")
      }
    })
  }
})
```

Demo: https://codepen.io/themustafaomar/pen/VwWagKV

Regards.

**Comment by crystalenka** [comment]
Amazing, thank you so much for your fast response and help!! I really appreciate it!

**Comment by crystalenka** [comment]
So I just tested the fix, and it fixes it a little too well! 😅 I use a trackpad and if I accidentally drag by like a pixel when trying to select a region, it no longer does it. I think this might also be an issue on touch devices although I haven't tried it yet. 

Is there way to add (or set) a threshold for dragging vs selecting action when both these options are enabled? Like if it drags more than, say, 10 or 20 pixels probably it's intentional, but under that might just be a sloppy click.

**Comment by themustafaomar** [comment]
Sorry for the very late response.

Although this isn't considered a big issue, I mean it's very difficult to move the cursor 1px or even 5px and very rare condition, but I'll see what I can do.

**Comment by crystalenka** [comment]
That’s what I’m saying - it happens on accident, and usually with a
trackpad or touch device. :) some kind of threshold that I could define to
understand motion as accidental or intentional would be amazing.

Also, please don’t apologize. It’s okay!! I know how open source goes and I
appreciate that you’re maintaining it at all. ❤️

Thank you!!

**Comment by themustafaomar** [comment]
Thank you for the kind words! It'll be fixed it as soon as possible.

**Comment by crystalenka** [comment]
Thank you!
