### ISSUE TITLE
zoomOnScroll not working on firefox

### ISSUE THREAD

**Issue by panpansh** [themustafaomar/jsvectormap#5]
Hello,
just checked your project as an alternative of jvectormap because I don't want jquery.
Like I said in the title zoomOnScroll not working on firefox where chrome  works.
Regards.

**Comment by panpansh** [comment]
on physical mobile it's the same for both firefox and chrome + draggable not working.

**Comment by themustafaomar** [comment]
Thank you for reporting this.
I've just updated the package with these fixes, please update to the version 1.0.6, and let me know if there is something not working.

**Comment by panpansh** [comment]
oh you so fast thanks I will check.
Regards

**Comment by panpansh** [comment]
Firefox seems to be fixed,
but using "bindTouchEvents: true," for smartphones => firefox and chrome on android = don't work well : I see just one time zoom and then after, nothing more displacement or zoom.

**Comment by themustafaomar** [comment]
Yes, you're right
Since the problem is in smartphones I'll need some time to fix this because this is incredibly complicated, and actually I've got a lot of work **:(** so I wish this fix may be available by the next week.

**Comment by themustafaomar** [comment]
@panpansh I think it's working now check this before committing.
https://jsvectormap.herokuapp.com/

**Comment by panpansh** [comment]
Exactly here it's working

**Comment by panpansh** [comment]
can you push sources please ?
using your minified version seems good 👍

**Comment by themustafaomar** [comment]
Done! please update to 1.0.7, see you in the next issue :D
