### ISSUE TITLE
Scrolling on the map doesn't stop scrolling on the page

### ISSUE THREAD

**Issue by kajgiesbersflavour** [themustafaomar/jsvectormap#50]
Since updating jsvectormap to 1.3, when scrolling on the map, the page scrolls too. This causes weird behaviour.

I have fixed this on our branch with this change: https://github.com/kajgiesbersflavour/jsvectormap/commit/66e91a6acc1f3df0da5693ee781e5484025fb0f6

I made a sample to show the issue here: https://github.com/kajgiesbersflavour/jsvectormap/commit/ea678a208461672720687d0a1595a095be54633a

Try zooming in and out on that sample page without the fix and you will see what I mean. 

I am not sure removing the `passive: true` can cause any issues, but I haven't found any and it seems to fix the problem for us.

**Comment by themustafaomar** [comment]
Well, apparently this is a bug.

This fix will be applied on the next version, you're welcome to send a PR.

The `passive` option will be removed as well.

Thank you!

**Comment by kajgiesbersflavour** [comment]
Thanks! I will make a pull request
