### ISSUE TITLE
tooltips and html

### ISSUE THREAD

**Issue by studiosacchetti** [themustafaomar/jsvectormap#57]
hello
it seems that tooltip does not support html anymore, am i wrong?

`tooltip.text("<h3>test</h3>");`  show `<h3>test</h3>`

**Comment by mateo9** [comment]
@studiosacchetti 
Did you found solution for this? Thanks

**Comment by themustafaomar** [comment]
Hey, sorry for the late response, I forgot to mention the tooltip changes in *BREAKING CHANGES*, gonna update this very soon.

However, the tooltip now is an instance of a Tooltip class, you can access the tooltip element like so, and do whatever you want:

![image](https://user-images.githubusercontent.com/46113191/146010490-560f4570-39cf-4d3b-a659-df8242074b84.png)
