### ISSUE TITLE
How i can add line on click ?

### ISSUE THREAD

**Issue by FoobarIT** [themustafaomar/jsvectormap#59]

**Comment by themustafaomar** [comment]
https://codepen.io/themustafaomar/pen/xxXLGvQ

**Comment by FoobarIT** [comment]
Thanks but can't use it out of map property ?

**Comment by themustafaomar** [comment]
Yes, feel free to move the listener outside the map.

https://codepen.io/themustafaomar/pen/xxXLGvQ

**Comment by FoobarIT** [comment]
Thanks for answer :)

**Comment by FoobarIT** [comment]
Possible see how selected region/marker/line ? I dont know how get index of region..

**Comment by themustafaomar** [comment]
You can't select lines, but you can select regions via regions codes:

https://themustafaomar.com/open-source/jsvectormap/docs/regions#selected-regions
