### ISSUE TITLE
tooltip.css() throws error

### ISSUE THREAD

**Issue by Flavsditz** [themustafaomar/jsvectormap#62]
First of all thanks so much for this library!

I am using the Vue wrapper for it and finding my way to achieve the necessary functionality in my project. One of them is that The tooltip should have different colors for selected vs unselected regions.

I've tried some hacks such as:

```typescript
regionTooltipShow(tooltip: any, code: any) {
    const color = this.selectedRegions.includes(code) ? "red" : "green";

    tooltip.getElement().style.cssText =
      `background-color: ${color};` + tooltip.getElement().style.cssText;
    tooltip.text(tooltip.text() + " (Hello this is a modified text!)");
  }
```

or

```typescript
regionTooltipShow(tooltip: any, code: any) {
    tooltip._tooltip.style.backgroundColor = "red";
    tooltip.text(tooltip.text() + " (Hello this is a modified text!)");
  }
```

to make the color change work and unfortunately, it doesn't!

The reason why I am trying to "hack it" is due to the fact that the `tooltip.css()` usage such as described on the docs doesn't work (throws an error saying that tooltip.css is not a function since it is undefined). I've noticed that the tooltip class implements the `text()` but not the `css()` functions.

Is something like the snippet below maybe missing?
```javascript
css(styles: Object) {
    if(!styles) {
      return this._tooltip.style;
    }

    for (const [key, value] of Object.entries(styles)) {
      this._tooltip.style[key] = value;
    }
  }
````
(Also changes to `handleElementEvents` around line 45 and others)
If so I am happy to create a MR and later even create an MR in the vue wrapper. I just like to know if there is something I might be missing

**Comment by Flavsditz** [comment]
Btw just in case someone wants to do something similarly:

I ended up solving by using extra classes
```typescript
regionTooltipShow(tooltip: any, code: any) {
    const included = this.selectedRegions.includes(code);

    if (included) {
      tooltip.getElement().classList.add("selected");
    } else {
      tooltip.getElement().classList.remove("selected");
    }
  }
```

and defining these on my SCSS file:
```scss
$tooltip-bg-color: #AAB3AE;

@import "~jsvectormap/src/scss/jsvectormap.scss";

.jvm-tooltip.selected{
  background-color: red;
}

```

**Comment by themustafaomar** [comment]
Hi @Flavsditz 

I was working on the `tooltip` and modified a lot of logic inside, I remove `css` function but I forgot to mention this in `breaking changes` in the docs, but since this feature is requested I'll roll it back immediately in the next version!

Thank you!

**Comment by Flavsditz** [comment]
Alright sounds good! I will be looking forward to that!
