### ISSUE TITLE
on window resize scale

### ISSUE THREAD

**Issue by panpansh** [themustafaomar/jsvectormap#7]
Here is how I do when window is resized (not a bug) it's just to share (AND if you have a better way let me know :)

```javascript
    jsvmap = new JsVectorMap({
        //...
    });

    // window on resize
    var resizeMapTimer;
    window.addEventListener('resize', function(e) {
        clearTimeout(resizeMapTimer);
        resizeMapTimer = setTimeout(function() {
            jsvmap.height = window.innerHeight;
            $("#map svg").setAttribute("height", window.innerHeight);
            jsvmap.width = window.innerWidth;
            $("#map svg").setAttribute("width", window.innerWidth);
            jsvmap.baseScale = 1;
            //console.log(jsvmap);
        }, 250);
    });

    // Trigger resize event one time at start
    if (typeof(Event) === 'function') {
        // modern browsers
        window.dispatchEvent(new Event('resize'));
    } else {
        // for IE and other old browsers
        // causes deprecation warning on modern browsers
        var evt = window.document.createEvent('UIEvents'); 
        evt.initUIEvent('resize', true, false, window, 0); 
        window.dispatchEvent(evt);
    }
```

**Comment by themustafaomar** [comment]
You can use `updateSize` method to handle that instead.
you will need to set the height and width to fit your needs and update size, here is an example:
```js
const map = new JsVectorMap({ ... })

window.addEventListener('resize', () => {
  if (window.innerWidth < 768) {

    // Using built-in DOM manipulation class for jsvectormap to set css properties.
    map.container.css({
      width: (window.innerWidth - 50)+'px',
      height: (window.innerHeight - 50)+'px'
    })

    map.updateSize()
  }
})
```
But what about a fully responsive jsvectormap?
Please take a look at this [Pen](https://codepen.io/themustafaomar/pen/VwedOyK).

**Comment by panpansh** [comment]
Nice thanks 👍 
I will check it tomorrow.

oh, you mean to have the map in fullscreen ?
if yes you just need this css :
```css
body {
  background-color: #f8f9fa;
}

#map {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}
```

**Comment by themustafaomar** [comment]
Nope! it was an example ([the pen](https://codepen.io/themustafaomar/pen/VwedOyK)) for anyone who wants to know how to make the jsvectormap responsive, thanks.

I wanted to make the map equal to the window width minus 50px and the height as well, you can ignore that.

**Comment by panpansh** [comment]
ok np,
using : (map||jsvmap).updateSize() : this.container is undefined
Did I miss something :pray:

**Comment by themustafaomar** [comment]
Can you share the code, at Codepen, please.

**Comment by panpansh** [comment]
yes : https://jsfiddle.net/kd8m0ew2/
it works my bad :pray:

**Comment by themustafaomar** [comment]
Unfortunately, I won't be able to find a solution currently as time is not on my side :(
However, I'll leave this issue opened until I come :]

**Comment by hanc2006** [comment]
@themustafaomar I forked your pen example, now seem to work right :+1: 
[responsive map](https://codepen.io/hanc2006/pen/NWxZJeZ)
