### ISSUE TITLE
Split visiblity options for tooltips

### ISSUE THREAD

**Issue by CosmoFox** [themustafaomar/jsvectormap#74]
Good day for all of you and really tnx for your project!
I suggest splitting the "showTooltip" option into two - one for map tooltips and one for markers.
Expected Result:
```
showTooltip: false
showMarkerTooltip: true
```
For allows to show tooltips only for markers.

**Comment by themustafaomar** [comment]
For now there is a good solution for disabling tooltip for markers.

```js
const map = new jsVectorMap({
  onMarkerTooltipShow(event, tooltip, code) {
    event.preventDefault()
  }
})
```

**Comment by CosmoFox** [comment]
Main idea was show tool tip only for markers, and not for map regions. So it's not a solution.

**Comment by themustafaomar** [comment]
Ah, sorry, I made it the other way around, it should be like this:

https://codepen.io/themustafaomar/pen/VwXjbJe

```js
const map = new jsVectorMap({
  onRegionTooltipShow(event, tooltip, code) {
    event.preventDefault()
  }
})
```
