### ISSUE TITLE
How can we return a html for the marker's ?

### ISSUE THREAD

**Issue by sunil-sabat** [themustafaomar/jsvectormap#77]
Hey there,
i have been trying to figure out if we could return the html for the marker 
we can change the labels html by selecting it but can we do the same with the markers ? 
i want to have a custom marker but i cant find any api for that i seem to remember that there was some kind of html() method in jvectormap. is it there on jsvectormap as well ?

thanks

**Comment by bitbruder** [comment]
If a simple image is enough for you, I just figured this out myself: https://github.com/themustafaomar/jsvectormap/issues/82

https://github.com/themustafaomar/jsvectormap/blob/master/samples/advanced.html#L70

**Comment by themustafaomar** [comment]
Unfortunately not, that's a bit complicated to implement currently.
