### ISSUE TITLE
Rebuild (regenerate) maps

### ISSUE THREAD

**Issue by CosmoFox** [themustafaomar/jsvectormap#80]
Hello!
Current maps have old geopolitics borders. So i was try to regenerate it with manuals from mother-project "jvectormap" and new map file from naturalearthdata.com (site from manual).
After a few day of bloody battle with old scripts for python2, and tonns of old requerments (GDAL/OGR was born in Hell).. I got a result on my virtual machine. 
And now i stand face-to-face with another problem. Format of final JSON map file. It`s really diffrent from yours in src folder (I attached new map file, which i got from manual. Difference in "" styling.).

I used temporaly workaround -  copied only vector coordinates to your map file of new regions borders.

So.. may be U have a secret way to build new map in right format? Maybe Py3 native way? 

[newworld.zip](https://github.com/themustafaomar/jsvectormap/files/8358026/newworld.zip)

**Comment by themustafaomar** [comment]
> After a few day of bloody battle with old scripts for python2, and tonns of old requerments (GDAL/OGR was born in Hell).. I got a result on my virtual machine. 😅

I understand the suffering you went through.

Anyway, simply you have to wrap the configuration object in something like that:

// worldnew.js

```js
jsVectorMap.addMap('YOUR_MAP_NAME', {
  // ..
})
```

Also I believe you can edit the jvectormap converter by replacing:

```js
jQuery.fn.vectorMap('addMap', 'world_mill', {
  // ..
})

// To be

jsVectorMap.addMap('YOUR_MAP_NAME', {
  // ..
})
```

**Comment by CosmoFox** [comment]
Thanks, I'll try your option. And little bit later, I'll do a pull reguest with a new world map.

**Comment by themustafaomar** [comment]
You're welcome.
