### ISSUE TITLE
Adding Custom Marker Images

### ISSUE THREAD

**Issue by bitbruder** [themustafaomar/jsvectormap#82]
Hey @themustafaomar !

First Off: Thank you very much for porting the original project to this vanilla based one. Awesome work!

I just wanted to add some custom marker styles like I was able in jvectormap

Example: https://jvectormap.com/examples/marker-icons/

Is this possible with jsvectormap? 

Im not sure if this line would make something like this possible:

https://github.com/themustafaomar/jsvectormap/blob/61d2f5e92d6b17c4b1d110147f5c4164b570d162/src/js/elements/marker.js#L14

Thanks for creating this awesome version!

**Comment by bitbruder** [comment]
Ha, found the answer myself. You used it in the "advanced" example.

https://github.com/themustafaomar/jsvectormap/blob/master/samples/advanced.html#L70

**Comment by themustafaomar** [comment]
Sorry for the late response, I think you found the solution yourself, good for you! 🎉
