### ISSUE TITLE
dist needs compiling

### ISSUE THREAD

**Issue by SimZal** [themustafaomar/jsvectormap#9]
Hello, I think setFocus is missing from compiled files in /dist

**Comment by themustafaomar** [comment]
Hi @SimZal 

Yes, the Github repository dist needs compiling lots of things.
but npm is up to date [https://unpkg.com/jsvectormap@1.0.7/dist/js/jsvectormap.js](https://unpkg.com/jsvectormap@1.0.7/dist/js/jsvectormap.js) and this is what we should care about.

Updating dist on Github each commit or each requested feature not a good idea and not important.
if you're cloning the repo and want dist gets updated just run `npm build`.

If you're using CDN links use the following links:
https://unpkg.com/jsvectormap
https://unpkg.com/jsvectormap@1.0.7/dist/maps/world.js
https://unpkg.com/jsvectormap@1.0.7/dist/css/jsvectormap.min.css

**Comment by SimZal** [comment]
Great, I will use that. Thank you.
