### ISSUE TITLE
tooltip.getElement() and tooltip.text() don't work anymore

### ISSUE THREAD

**Issue by square-theme** [themustafaomar/jsvectormap#90]
Hi, since the update of 1.5.0 I get errors for both, this is my code which worked before:
```
onMarkerTooltipShow(tooltip, index) {
    tooltip.getElement().innerHTML = `${tooltip.text()}<br/>${
        worldMapMarkers[index].description || ''
    `;
}
```
What do I need to change to make it work again?

**Comment by themustafaomar** [comment]
Thanks for reporting this, I think I forgot to mention this change in the breaking changes.

Simply `onMarkerTooltipShow` is now receives the native event as the first argument.

https://codepen.io/themustafaomar/pen/JjLKzmK

```js
onMarkerTooltipShow(event, tooltip, index) {
    tooltip.getElement().innerHTML = `${tooltip.text()}<br/>${worldMapMarkers[index].description || ''}`
}
```

**Comment by levipadre** [comment]
Thank you very much @themustafaomar !
