### ISSUE TITLE
Can I reset the map style?

### ISSUE THREAD

**Issue by levipadre** [themustafaomar/jsvectormap#91]
Hi, I have a map with custom markerStyle and regionStyle, which are using css variables.
These css variables are changing when you switch to dark mode. Unfortunately the map doesn't reload.
I tried with reset function but it didn't work:

```
const map = new jsVectorMap(options);

window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
    map.reset();
});
```

Is there a way to reset/reload the map or config?

**Comment by themustafaomar** [comment]
From my point of view, I see that the best way to achieve this by simply using CSS.

https://codepen.io/themustafaomar/pen/dympaoq

Related issue: #41
